[build]
  command = "pnpm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions-internal"
  
[[headers]]
  for = "/**"
  [headers.values]
    Cache-Control = "public, s-maxage=3600, stale-while-revalidate=86400"

